Repository bcgsc/pori_graphkb_loader, pull requests merged in 2021-07, with the labels that each got.

#17 Release/v5.1.1
  README.md
  package-lock.json
  package.json
  src/civic/index.js
  src/civic/variant.js
  src/graphkb.js
  test/civic.test.js
Labels: release

#18 Feature/trusted curators
  bin/load.js
  package.json
  src/civic/README.md
  src/civic/index.js
Labels: enhancement

#22 fix(ncit): fix subclass relationship loader
  bin/load.js
  src/ncit/index.js
Labels: bug, enhancement

#23 Feature/source add function
  src/PMC4468049/index.js
  src/cancergenomeinterpreter/index.js
  src/cancerhotspots/index.js
  src/cgl/index.js
  src/chembl/index.js
  src/civic/index.js
  src/clinicaltrialsgov/index.js
  src/cosmic/fusions.js
  src/cosmic/resistance.js
  src/dgidb/index.js
  src/diseaseOntology/index.js
  src/docm/index.js
  src/drugbank/index.js
  src/ensembl/index.js
  src/entrez/util.js
  src/fdaApprovals/index.js
  src/fdaSrs/index.js
  src/graphkb.js
  src/gscTherapeuticOntology.js
  src/hgnc/index.js
  src/ncit/index.js
  src/ncit/ncitFdaXref.js
  src/oncokb/index.js
  src/oncotree/index.js
  src/ontology/index.js
  src/sequenceOntology.js
  src/uberon/index.js
  src/vario.js
  test/loadfile.test.js
  test/loadrecords.test.js
Labels: enhancement
