Repository bcgsc/pori_graphkb_loader, pull requests merged in 2022-04, with the labels that each got.

#89 Fix critical audit vulnerabilities
  package-lock.json
  package.json
Labels: security

#83 Fix uploadRecord in hgnc loader for alias_symbol
  src/hgnc/index.js
Labels: bug

#91 Only run audit on merge to master
  .github/workflows/npm-test.yml
Labels: devops, security
