Repository bcgsc/pori_graphkb_loader, pull requests merged in 2022-03, with the labels that each got.

#73 Release/v6.2.0
  .github/workflows/npm-test.yml
  .gitignore
  Dockerfile
  README.md
  Snakefile
  bin/load.js
  data/evidenceLevels.json
  data/vocab.json
  docs/basic_workflow.png
  docs/full_workflow.png
  package-lock.json
  package.json
  src/asco/index.js
  src/asco/specs.json
  src/cancergenomeinterpreter/index.js
  src/chembl/index.js
  src/chembl/spec.json
  src/civic/README.md
  src/civic/index.js
  src/civic/specs.json
  src/civic/variant.js
  src/cli.js
  src/clinicaltrialsgov/index.js
  src/clinicaltrialsgov/specs.json
  src/cosmic/fusions.js
  src/cosmic/resistance.js
  src/dgidb/index.js
  src/dgidb/spec.json
  src/diseaseOntology/index.js
  src/diseaseOntology/specs.json
  src/docm/index.js
  src/docm/specs.json
  src/drugbank/index.js
  src/drugbank/spec.json
  src/fdaApprovals/index.js
  src/fdaSrs/index.js
  src/graphkb.js
  src/hgnc/index.js
  src/moa/README.md
  src/moa/index.js
  src/moa/spec.json
  src/ncit/README.md
  src/ncit/index.js
  src/oncokb/index.js
  src/oncotree/index.js
  src/ontology/index.js
  src/refseq/index.js
  src/sources.js
  src/uberon/index.js
  src/util.js
  test/civic.test.js
  test/graphkb.test.js
  test/moa.test.js
  test/ncit.test.js
  test/util.test.js
Labels: release

#75 Feature/entrez gene tests
  Snakefile
  package-lock.json
  package.json
  src/util.js
  test/data/external_api_responses.json
  test/entrez/gene.test.js
Labels: tests

#81 Fix linkFeatureToParent() in ensembl loader
  src/ensembl/index.js
Labels: bug
