Repository bcgsc/pori_graphkb_loader, pull requests merged in 2022-01, with the labels that each got.

#40 Add mapping of terms/fields from civic to GraphKB
  src/civic/README.md
Labels: documentation

#62 Feature/moa support
  README.md
  Snakefile
  bin/load.js
  data/evidenceLevels.json
  data/vocab.json
  package-lock.json
  package.json
  src/civic/index.js
  src/civic/variant.js
  src/dgidb/index.js
  src/docm/index.js
  src/fdaApprovals/index.js
  src/graphkb.js
  src/hgnc/index.js
  src/moa/README.md
  src/moa/index.js
  src/moa/spec.json
  src/oncokb/index.js
  src/oncotree/index.js
  src/ontology/index.js
  src/sources.js
  src/util.js
  test/moa.test.js
Labels: enhancement

#63 Feature/node 16
  .github/workflows/npm-test.yml
  Snakefile
  bin/load.js
  src/asco/index.js
  src/asco/specs.json
  src/cancergenomeinterpreter/index.js
  src/chembl/index.js
  src/chembl/spec.json
  src/civic/index.js
  src/civic/specs.json
  src/civic/variant.js
  src/cli.js
  src/clinicaltrialsgov/index.js
  src/clinicaltrialsgov/specs.json
  src/cosmic/fusions.js
  src/cosmic/resistance.js
  src/dgidb/index.js
  src/dgidb/spec.json
  src/diseaseOntology/index.js
  src/diseaseOntology/specs.json
  src/docm/index.js
  src/docm/specs.json
  src/drugbank/index.js
  src/drugbank/spec.json
  src/fdaSrs/index.js
  src/hgnc/index.js
  src/moa/README.md
  src/ncit/index.js
  src/refseq/index.js
  src/uberon/index.js
Labels: bug, enhancement, devops

#64 Feature/civic unaltered function
  data/vocab.json
  src/civic/index.js
  src/civic/specs.json
  test/civic.test.js
Labels: enhancement, CIViC

#65 Improve getting started docs
  README.md
  package.json
Labels: documentation
